**Problem Statement**
Motion Studios is the largest radio production house in Europe. Its total revenue is $1B+. The company has launched a new reality TV show called "The Star Rj". The show is about finding a new radio jockey who will bee the star presenter on upcoming shows. In the first round, participants will have to upload their voice clips online. The clip will be evaluated by experts for selection to the next round. There is  a separate team in the forst round for evaluation of male and female voices.

Also, the response to the show is unpredicted,and the company is flooded with voice clips.

As a result of all this, there is a need to classify the voice as either male or female so that the first level of filtration is quicker.

In [ ]:
import pandas as pd
import numpy as numpy
import matplotlib.pyplot as plt #to perform visualization tasks
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [26]:
df = pd.read_csv('/content/voice.csv')#loading the dataset
df.head()#prints the top 5 entries from dataset

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000   male  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632   male  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512   male  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119   male  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274   male  

[5 rows x 21 columns]

In [27]:
df.info()#dives the information about the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3168 entries, 0 to 3167
Data columns (total 21 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   meanfreq  3168 non-null   float64
 1   sd        3168 non-null   float64
 2   median    3168 non-null   float64
 3   Q25       3168 non-null   float64
 4   Q75       3168 non-null   float64
 5   IQR       3168 non-null   float64
 6   skew      3168 non-null   float64
 7   kurt      3168 non-null   float64
 8   sp.ent    3168 non-null   float64
 9   sfm       3168 non-null   float64
 10  mode      3168 non-null   float64
 11  centroid  3168 non-null   float64
 12  meanfun   3168 non-null   float64
 13  minfun    3168 non-null   float64
 14  maxfun    3168 non-null   float64
 15  meandom   3168 non-null   float64
 16  mindom    3168 non-null   float64
 17  maxdom    3168 non-null   float64
 18  dfrange   3168 non-null   float64
 19  modindx   3168 non-null   float64
 20  label     3168 non-null   obje

In [ ]:
df.describe()#describes te fxn to get the information about te dataset

meanfreq           sd       median          Q25          Q75  \
count  3168.000000  3168.000000  3168.000000  3168.000000  3168.000000   
mean      0.180907     0.057126     0.185621     0.140456     0.224765   
std       0.029918     0.016652     0.036360     0.048680     0.023639   
min       0.039363     0.018363     0.010975     0.000229     0.042946   
25%       0.163662     0.041954     0.169593     0.111087     0.208747   
50%       0.184838     0.059155     0.190032     0.140286     0.225684   
75%       0.199146     0.067020     0.210618     0.175939     0.243660   
max       0.251124     0.115273     0.261224     0.247347     0.273469   

               IQR         skew         kurt       sp.ent          sfm  \
count  3168.000000  3168.000000  3168.000000  3168.000000  3168.000000   
mean      0.084309     3.140168    36.568461     0.895127     0.408216   
std       0.042783     4.240529   134.928661     0.044980     0.177521   
min       0.014558     0.141735     2.068455     0.738651     0.036876   
25%       0.042560     1.649569     5.669547     0.861811     0.258041   
50%       0.094280     2.197101     8.318463     0.901767     0.396335   
75%       0.114175     2.931694    13.648905     0.928713     0.533676   
max       0.252225    34.725453  1309.612887     0.981997     0.842936   

              mode     centroid      meanfun       minfun       maxfun  \
count  3168.000000  3168.000000  3168.000000  3168.000000  3168.000000   
mean      0.165282     0.180907     0.142807     0.036802     0.258842   
std       0.077203     0.029918     0.032304     0.019220     0.030077   
min       0.000000     0.039363     0.055565     0.009775     0.103093   
25%       0.118016     0.163662     0.116998     0.018223     0.253968   
50%       0.186599     0.184838     0.140519     0.046110     0.271186   
75%       0.221104     0.199146     0.169581     0.047904     0.277457   
max       0.280000     0.251124     0.237636     0.204082     0.279114   

           meandom       mindom       maxdom      dfrange      modindx  
count  3168.000000  3168.000000  3168.000000  3168.000000  3168.000000  
mean      0.829211     0.052647     5.047277     4.994630     0.173752  
std       0.525205     0.063299     3.521157     3.520039     0.119454  
min       0.007812     0.004883     0.007812     0.000000     0.000000  
25%       0.419828     0.007812     2.070312     2.044922     0.099766  
50%       0.765795     0.023438     4.992188     4.945312     0.139357  
75%       1.177166     0.070312     7.007812     6.992188     0.209183  
max       2.957682     0.458984    21.867188    21.843750     0.932374

In [ ]:
df.isnull().sum()#to check any null value in the dataset

meanfreq    0
sd          0
median      0
Q25         0
Q75         0
IQR         0
skew        0
kurt        0
sp.ent      0
sfm         0
mode        0
centroid    0
meanfun     0
minfun      0
maxfun      0
meandom     0
mindom      0
maxdom      0
dfrange     0
modindx     0
label       0
dtype: int64

In [ ]:
print("Shape of Data",df.shape)#get the shape of our data so as o recoerd the total no. of labels
print("Total number of labels: {}".format(df.shape[0]))
print("Number of male: {}".format(df[df.label=='male'].shape[0]))#record the total no. of males
print("Number of female: {}".format(df[df.label=='female'].shape[0]))#record the total no. of females

Shape of Data (3168, 21)
Total number of labels: 3168
Number of male: 1584
Number of female: 1584


In [ ]:
X = df.iloc[:,:-1]#Extract the target variable within X
print(df.shape)
print(X.shape)

(3168, 21)
(3168, 20)


In [ ]:
from sklearn.preprocessing import LabelEncoder#we can use label encoder to extract the value of last column within y

In [ ]:
y = df.iloc[:,-1]

gender_encoder = LabelEncoder()#and initialize the label encoder
y = gender_encoder.fit_transform(y)#Here we are going to encode the categorical labels, so that male gets encoded to "1" and female gets encoded to "0"
y

array([1, 1, 1, ..., 0, 0, 0])

In [ ]:
#now to make the model efficient we will have to scale the training data b/w "0" and "1"
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()#initializing the standard scaler
scaler.fit(X)#fit the scaler over the training data
X = scaler.transform(X)#using transform fxn to apply the transformation on X

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=100)#Splitting the data b/w training and test sets such that the training to testing ratio is 70% or 30%

In [ ]:
#Now its time to train a SVM classifier
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.svm import SVC#calling the SVC model from sklearn for fitting the model for trining data
from sklearn import metrics
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
svc_model = SVC()#initializing the SVC model
svc_model.fit(X_train,y_train)#fit the SVC model on training sets
y_pred = svc_model.predict(X_test)#get predictions from model and print accuracy

In [ ]:
print('Accuracy Score:')
print(metrics.accuracy_score(y_test,y_pred))

Accuracy Score:
0.9737118822292324


In [ ]:
#Creating confusion matrix and classification report with respect to y
print(confusion_matrix(y_test,y_pred))

[[458  13]
 [ 12 468]]


In [ ]:
#We must create this using a Grid Search also
from sklearn.model_selection import GridSearchCV

In [ ]:
#Create a dictionary called param grid and fill out some parameters for C and gamma
param_grid = {'C': [0,1,1,10,100],'gamma':[1,0.1,0.01,0.001]}

In [ ]:
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=2)#Initializing the grid search CV MODEL such that refit is = to true and verbose is = 2
#The parameter refit refits in estimator using the best found parameters on the whole datas set
grid.fit(X_train,y_train)#Fit the grit search model on training sets

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[CV] END .......................................C=0, gamma=1; total time=   0.0s
[CV] END .......................................C=0, gamma=1; total time=   0.0s
[CV] END .......................................C=0, gamma=1; total time=   0.0s
[CV] END .......................................C=0, gamma=1; total time=   0.0s
[CV] END .......................................C=0, gamma=1; total time=   0.0s
[CV] END .....................................C=0, gamma=0.1; total time=   0.0s
[CV] END .....................................C=0, gamma=0.1; total time=   0.0s
[CV] END .....................................C=0, gamma=0.1; total time=   0.0s
[CV] END .....................................C=0, gamma=0.1; total time=   0.0s
[CV] END .....................................C=0, gamma=0.1; total time=   0.0s
[CV] END ....................................C=0, gamma=0.01; total time=   0.0s
[CV] END ....................................C=

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0, 1, 1, 10, 100],
                         'gamma': [1, 0.1, 0.01, 0.001]},
             verbose=2)

In [ ]:
grid_predictions = grid.predict(X_test)#taking the grid model and creating some predictions using the test set

In [ ]:
print('Accuracy Score:')#calculete the accuracy score for the same
print(metrics.accuracy_score(y_test,grid_predictions))

Accuracy Score:
0.9747634069400631


In [ ]:
print(confusion_matrix(y_test,grid_predictions))#also create classification reports and confusion matrix for them w.r.t y_test,grid_predictions

[[459  12]
 [ 12 468]]


In [ ]:
print(classification_report(y_test,grid_predictions))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97       471
           1       0.97      0.97      0.97       480

    accuracy                           0.97       951
   macro avg       0.97      0.97      0.97       951
weighted avg       0.97      0.97      0.97       951



what we done!!!

1.Import libraries and the dataset

2.Check for missing values

3.Check the distribution of the dataset

4.Preprocess theh data using label encoders

5.Fit SVM classifier on the transformed data

6.Print the accuracy, confusion matrix and classification report

7.Use grid search to optimize the results further

8.Print the accuracy, confusion matrix and classification report of the optimized model